### ISSUE TITLE
文档: `docs/guide/advanced.html`文件中的`cick`拼错了，应该是`click`

### ISSUE THREAD

**Issue by gogoend** [wechat-miniprogram/wechat-miniprogram.github.io#4]
这是所在行：

https://github.com/wechat-miniprogram/wechat-miniprogram.github.io/blob/2d5615ddda6a4c5ea01079ab7a530760fbb9632a/kbone/docs/guide/advanced.html#L314

**Comment by JuneAndGreen** [comment]
fixed。
